### ISSUE TITLE
Downcast doesn't play nicely with minification

### ISSUE THREAD

**Issue by kegsay** [matrix-org/matrix-rust-sdk-crypto-wasm#51]
[This function](https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/blob/207c54a41b647be1df65b9b584f20c0a07a0b42d/src/js.rs#L9) looks at constructor names to try to determine the right types. Specifically:
```rust
let constructor_name = Object::get_prototype_of(value).constructor().name();
```
This may return an unexpected constructor name when minification has been used, as classes are renamed to shorter strings e.g `UserId` becomes `NG`. This can then cause confusing errors:

```
Error: Expect an `UserId` instance, received `Ng` instead
```

**Comment by Hywan** [comment]
With https://github.com/rustwasm/wasm-bindgen/pull/3554, it might no longer be necessary to play with `downcast` here, as it's primarily used for supporting `Vec<T>` as far as I know.

**Comment by Hywan** [comment]
A new release of `wasm-bindgen` has been made yesterday, perfect.

**Comment by richvdh** [comment]
> A new release of `wasm-bindgen` has been made yesterday, perfect ([0.2.88](https://github.com/rustwasm/wasm-bindgen/blob/main/CHANGELOG.md)).

Yes, though give we have custom `impl From<X> for JsValue` implementations for various of our pipes, it seems to cause damage for us in much the same way as https://github.com/rustwasm/wasm-bindgen/issues/3685.

**Comment by richvdh** [comment]
This is going to be a blocker for full release of Element R, because normal builds use minified source.

**Comment by Hywan** [comment]
Do you need my help here?

**Comment by richvdh** [comment]
> Do you need my help here?

Any help would be much appreciated.

At the moment, my ideas are:

 * Get rid of the check on the constructor name altogether, and just assume that the application side has passed an object of the right type. Obviously, this will break *horribly* if they do not.
 * If we could somehow get hold of a `JsValue` holding an instance of an object known to be of the right type, then rather than hard-coding the constructor name, we could compare the two constructors. But we wouldn't want to create an object on the JS side for every call, so I don't think this works.

**Comment by richvdh** [comment]
Just for the record: We could have replaced `downcast` with `wasm_bindgen::convert::TryFromJsValue` (as introduced in https://github.com/rustwasm/wasm-bindgen/pull/3709), but:

(a) that's supposedly internal; 

(b) we don't need `downcast` at all since wasm-bindgen now supports properly-typed `Vec<...>` parameters that will check the values in the array at runtime (added in https://github.com/rustwasm/wasm-bindgen/pull/3554, as modified by https://github.com/rustwasm/wasm-bindgen/pull/3709)

**Comment by richvdh** [comment]
> Just for the record: We could have replaced `downcast` with `wasm_bindgen::convert::TryFromJsValue` (as introduced in [rustwasm/wasm-bindgen#3709](https://github.com/rustwasm/wasm-bindgen/pull/3709))

oh, in fact @Hywan's PR does exactly that in this instance: https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/82/commits/c556316057b346ad7b6a9d6b1303738a55f67c49#diff-dd97281cbaa3b13ed5a8dc4417797959632eed864b774977e013fc307dcc9f01L1002-R1012

**Comment by MTRNord** [comment]
There is also https://github.com/matrix-org/matrix-rust-sdk/compare/main...MTRNord:matrix-rust-sdk:MTRNord/fix-binding-reflection which is based on the wasmer code. However, afaik the repo for wasm-bindgen-downcast is still not public but the source on crates has a FOSS license as seen here: https://docs.rs/crate/wasm-bindgen-downcast/0.1.1/source/README.md 

The missing repo is at https://github.com/wasmerio/wasm-bindgen-downcast
